add ubuntu runner for caching

diff --git a/.github/workflows/cache_elephant_data.yml b/.github/workflows/cache_elephant_data.yml
--- a/.github/workflows/cache_elephant_data.yml
+++ b/.github/workflows/cache_elephant_data.yml
@@ -19,7 +19,13 @@ on:
 jobs:
     create-data-cache-if-missing:
         name: Caching data env
-        runs-on: "macos-latest"
+        runs-on: ${{ matrix.os }}
+        strategy:
+          # do not cancel all in-progress jobs if any matrix job fails
+          fail-fast: false
+          matrix:
+            # OS [ubuntu-latest, macos-latest, windows-latest]
+            os: [macos-latest,ubuntu-latest]
         steps:
     
           - name: Get current hash (SHA) of the elephant_data repo
@@ -43,8 +49,14 @@ jobs:
                 git config --global user.email "elephant_ci@fake_mail.com"
                 git config --global user.name "elephant CI"
                 git config --global filter.annex.process "git-annex filter-process"  # recommended for efficiency
-
-                brew install datalad
+                if [[ "$OSTYPE" == "darwin"* ]]; then
+                  brew install datalad
+                elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
+                  apt-get install datalad
+                else
+                  echo "Unsupported operating system."
+                  exit 1
+                fi
 
           - name: Download dataset
             id: download-dataset
