Test before reverting debugg commits

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -67,26 +67,26 @@ jobs:
 
       - uses: ./.github/actions/restore-elephant-data
 
-      # - name: Install dependencies
-      #   run: |
-      #     python -m pip install --upgrade pip
-      #     pip install coveralls
-      #     pip install -e .[extras,tests]
-      #
-      # - name: List packages
-      #   run: |
-      #     pip list
-      #     python --version
-      #
-      # - name: Test with pytest
-      #   shell: bash
-      #   run: pytest
-      #
-      # - name: Submit Coveralls
-      #   if: runner.os == 'Linux' && matrix.python-version == '3.12'
-      #   run: coveralls --service=github || echo "Coveralls submission failed"
-      #   env:
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install coveralls
+          pip install -e .[extras,tests]
+
+      - name: List packages
+        run: |
+          pip list
+          python --version
+
+      - name: Test with pytest
+        shell: bash
+        run: pytest
+
+      - name: Submit Coveralls
+        if: runner.os == 'Linux' && matrix.python-version == '3.12'
+        run: coveralls --service=github || echo "Coveralls submission failed"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   #  __  __ ____ ___
   # |  \/  |  _ \_ _|
