Temporarily disable all other jobs other than pip

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -67,26 +67,26 @@ jobs:
 
       - uses: ./.github/actions/restore-elephant-data
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install coveralls
-          pip install -e .[extras,tests]
-
-      - name: List packages
-        run: |
-          pip list
-          python --version
-
-      - name: Test with pytest
-        shell: bash
-        run: pytest
-
-      - name: Submit Coveralls
-        if: runner.os == 'Linux' && matrix.python-version == '3.12'
-        run: coveralls --service=github || echo "Coveralls submission failed"
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # - name: Install dependencies
+      #   run: |
+      #     python -m pip install --upgrade pip
+      #     pip install coveralls
+      #     pip install -e .[extras,tests]
+      #
+      # - name: List packages
+      #   run: |
+      #     pip list
+      #     python --version
+      #
+      # - name: Test with pytest
+      #   shell: bash
+      #   run: pytest
+      #
+      # - name: Submit Coveralls
+      #   if: runner.os == 'Linux' && matrix.python-version == '3.12'
+      #   run: coveralls --service=github || echo "Coveralls submission failed"
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   #  __  __ ____ ___
   # |  \/  |  _ \_ _|
@@ -102,7 +102,7 @@ jobs:
         python-version: ["3.12"]
         os: [ubuntu-latest]
       fail-fast: false
-
+    if: false
     steps:
       - uses: actions/checkout@v4.1.6
 
@@ -168,7 +168,7 @@ jobs:
 
       # do not cancel all in-progress jobs if any matrix job fails
       fail-fast: false
-
+    if: false
     steps:
       - name: Get current year-month
         id: date
@@ -247,7 +247,7 @@ jobs:
         python-version: [3.12]
         # OS [ubuntu-latest, macos-latest, windows-latest]
         os: [ubuntu-latest]
-
+    if: false
     steps:
 
       - name: Get current year-month
@@ -311,7 +311,7 @@ jobs:
 
         # OS [ubuntu-latest, macos-latest, windows-latest]
         os: [ubuntu-latest]
-
+    if: false
     steps:
       # used to reset cache every month
       - name: Get current year-month
