fix CI fail on coveralls report

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -110,7 +110,8 @@ jobs:
 
       - name: Test with pytest
         run: |
-          coverage run --source=elephant -m pytest && coveralls --service=github || echo "Coveralls submission failed"
+          coverage run --source=elephant -m pytest
+          coveralls --service=github || echo "Coveralls submission failed"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -298,7 +299,8 @@ jobs:
 
       - name: Test with pytest
         run: |
-          mpiexec -n 1 python -m mpi4py -m coverage run --source=elephant -m pytest && coveralls --service=github || echo "Coveralls submission failed"
+          mpiexec -n 1 python -m mpi4py -m coverage run --source=elephant -m pytest
+          coveralls --service=github || echo "Coveralls submission failed"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
